// Generated by CoffeeScript 1.6.1
var all, delay, query, show,
  __slice = [].slice;

show = function() {
  var args;
  args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
  return console.log.apply(console, args);
};

delay = function(t, f) {
  return setTimeout(f, t);
};

query = function(sign) {
  return document.querySelector(sign);
};

all = function(sign) {
  return document.querySelectorAll(sign);
};

window.onload = function() {
  var body, elem, nav, now, _i, _len, _results;
  body = document.body;
  nav = all('.title');
  now = function(n) {
    if (n != null) {
      return window.scrollTo(0, n);
    } else {
      return window.pageYOffset;
    }
  };
  _results = [];
  for (_i = 0, _len = nav.length; _i < _len; _i++) {
    elem = nav[_i];
    _results.push((function(elem) {
      elem.onclick = function(e) {
        var scoll, top;
        top = elem.parentNode.offsetTop;
        return (scoll = function() {
          return delay(10, function() {
            if ((Math.abs(top - now())) >= 300) {
              if (top > now()) {
                now(now() + 300);
                if (top > now()) {
                  return scoll();
                }
              } else if (top < now()) {
                now(now() - 300);
                if (top < now()) {
                  return scoll();
                }
              }
            } else {
              return now(top);
            }
          });
        })();
      };
      return elem.parentNode.onmouseover = function() {
        query('#bg').innerText = elem.innerText;
        return query('#bg').textContent = elem.textContent;
      };
    })(elem));
  }
  return _results;
};
