// Generated by CoffeeScript 1.3.3

$(function() {
  return $('.title').click(function(e) {
    var classes, h, name;
    classes = e.target.className;
    name = classes.split(' ')[1];
    h = $("#article>." + name).offset().top;
    return $("body").animate({
      scrollTop: h
    });
  });
});
